openapi: 3.0.1
info:
  $ref: ./generated/info.yaml
servers:
  $ref: ./generated/servers.yaml
tags:
  $ref: ./generated/tags.yaml
paths:
  $ref: ./generated/paths/paths-generated.yaml
components:
  # parameters:
    # $ref: ./generated/components/parameters/_index.yaml
  # requestBodies:
    # $ref: ./generated/components/request-bodies/_index.yaml
  schemas:
    $ref: ./generated/components/schemas/schemas-generated.yaml
    # responses:
    # $ref: ./generated/components/responses/_index.yaml
  # securitySchemes:
    # $ref: ./generated/components/security-schemes/_index.yaml
x-components: {}
