openapi: 3.0.1
info:
  title: Test API
  description: Test API description
  contacts:
    name: Simone Di Cicco
    email: simone.dicicco@gmail.com
  version: 1.0.0
servers:
  - url: 'http://api.test.com/'
tags:
  - name: Tag
    description: Description
paths:
  /test/hello-world:
    get:
      tags:
        - Test
      summary: Hello World
      operationId: helloWorld
      responses:
        '200':
          description: Hello World returned
          content:
            application/json; charset=utf-8:
              schema:
                allOf:
                  - type: object
                    properties:
                      test:
                        type: string
  /test/external:
    get:
      tags:
        - Test
      summary: External call
      operationId: external
      responses:
        '200':
          description: External call returned
          content:
            application/json; charset=utf-8:
              schema:
                allOf:
                  - type: object
                    properties:
                      external:
                        type: object
components:
  parameters: null
  requestBodies: null
  schemas:
    HelloWorldDto:
      type: object
      properties:
        test:
          type: string
    ExternalDto:
      type: object
      properties:
        external:
          type: object
  responses: null
  securitySchemes: null
x-components: {}

