name: CI

on:
  pull_request:
    types: [ready_for_review, synchronize, opened]
  push:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-test
      cancel-in-progress: true
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.0
          run_install: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "resolve style guide violations"
      - name: Unit test Framework
        run: cd "$GITHUB_WORKSPACE/packages/framework/" && pnpm test:coverage
      - name: Integration test Framework
        run: cd "$GITHUB_WORKSPACE/packages/framework/" && pnpm test:integration
      - name: Unit test DI
        run: cd "$GITHUB_WORKSPACE/packages/di/" && pnpm test:coverage
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update coverage badge"
