name: Test Unit

on:
  pull_request:
    types: [ready_for_review, synchronize, opened]
  push:
    branches: [main]

jobs:
  test-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    concurrency:
      group: ${{ github.head_ref }}-test-unit
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:coverage
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "test: update coverage badge"
